steps:
- name: 'asia.gcr.io/cloud-builders/mvn'
  args: ['install']
  #dir: '/resourcetechnologymapping'
- name: 'asia.gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['build', '--tag=asia.gcr.io/$PROJECT_ID/resourcetechnologymapping', '.']
  #args: ['build', '.']
# dir: '/resourcetechnologymapping'
