steps:
# Pull the latest gcloud image.
- name: 'gcr.io/mindtree-gcp-project-135/docker'
  args: ['pull', 'gcr.io/mindtree-gcp-project-135/resourcetechnologymapping']
- name: 'gcr.io/mindtree-gcp-project-135/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/resourcetechnologymapping', '.']

# Clone a public repo and write its revision to a VERSION file.
- name: 'gcr.io/$PROJECT_ID/resourcetechnologymapping'
  args: ['clone', 'git@github.com:Sakthi-Dhandapani-Mintree/backend-web-application.git']
  #dir:  './resourcetechnologymapping'
images: ['gcr.io/$PROJECT_ID/resourcetechnologymapping']
