steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install',"/workspace/resourcetechnologymapping"]
#- name: 'gcr.io/cloud-builders/mvn'
#  args: ['package']
- name: "gcr.io/cloud-builders/mvn"
  args: ["build", "/workspace/resourcetechnologymapping"]
timeout: "1600s"
