steps:
- name: 'asia.gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'resourcetechnologymapping'
- name: 'asia.gcr.io/cloud-builders/mvn'
  args: ['package']
steps:
# Pull the latest gcloud image.
- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['pull', 'asia.gcr.io/cloud-builders/gcloud']
- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['build', '--tag=asia.gcr.io/$PROJECT_ID/resourcetechnologymapping', '.']
