steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetechnologymapping'
artifacts:
  objects:
   location: 'gs://mindtreegcp/'
   paths:
    - "${_TARGET}"
   copy:
    src: gs://mindtreegcp/
    dest: M1048134@35.200.222.182:/usr/local/tomcat9/webapps/
