steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/gcloud"  
  args: [ 'compute', 'instances', 'create', 'front-end-instance-cb', '--image=gcp-backend-image', '--machine-type=n1-standard-1',--zone= us-central1-a ','--metadata=startup-script-url=gs://mindtree-gcp-project-135/startup-cloudbuild-script.sh' ]
artifacts:
  objects:
   location: 'gs://mindtreegcp/'
   paths:
   - "${_TARGET}"
