steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'resourcetechnologymapping'   
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
  dir: 'resourcetechnologymapping'
- name: 'gcr.io/cloud-builders/mvn'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/resourcetechnologymapping', '.']
  dir: 'resourcetechnologymapping'
timeout: "1600s"
