steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetechnologymapping'
artifacts:
  objects:
    location: 'gs://mindtreegcp/'
    paths:
    - "${_TARGET}"
- name:
    copy:
    src: gs://mindtree-gcp-project-135/
    dest: /usr/local/tomcat9/webapps
