steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/gcloud"  
  args: [ 'compute', 'instances', 'create', 'front-end-instance-cb', '--image=gcp-backend-image', '--image-family=gcp-backend-image', '--machine-type=n1-standard-1', '--metadata=startup-script-url=gs://mindtree-gcp-project-135/startup-cloudbuild-script.sh' ]
- name: example copying file with owner and permissions
    copy:
    src: /workspace/resourcetechnologymapping/target/resourcetechnologymapping.war
    dest: /usr/local/tomcat9/webapps
    owner: root
    group: root
    mode: 0644
artifacts:
  objects:
   location: 'gs://mindtreegcp/'
   paths:
   - "${_TARGET}"
