steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - tomcat9:run
  dir: 'resourcetechnologymapping'
artifacts:
  objects:
    location: 'gs://mindtreegcp/'
    paths:
    - "${_TARGET}"
