steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetechnologymapping'
artifacts:
  objects:
    location: "gs://${_BUCKET}/"
    paths:
    - "/workspace/resourcetechnologymapping/target/${_TARGET}"
    
    #/workspace/resourcetechnologymapping
