steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
#- name: 'gcr.io/cloud-builders/mvn'
#  args: ['package']
- name: "gcr.io/cloud-builders/mvn"
  args: ["build", "./resourcetechnologymapping"]
timeout: "1600s"
