steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetechnologymapping'
artifacts:
  objects:
    location: "gs://mindtreegcp/"
    paths:
    - "target/resourcetechnologymapping/${_TARGET}"
