# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#
# TODO(franklinn): Stop tagging java/mvn images once usage has dropped off.

steps:
# Build the java / maven matrix.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=gcr.io/$PROJECT_ID/javac:8'
  - '--build-arg=MAVEN_VERSION=3.3.9'
  - '--build-arg=SHA=6e3e9c949ab4695a204f74038717aa7b2689b1be94875899ac1b3fe42800ff82'
  - '--tag=gcr.io/$PROJECT_ID/mvn:3.3.9-jdk-8'
  - '--tag=gcr.io/$PROJECT_ID/java/mvn:3.3.9-jdk-8'
  - '.'
  wait_for: ['-']
# run examples
- name: 'gcr.io/$PROJECT_ID/mvn:3.3.9-jdk-8'
  args: ['install']
  dir: 'backend-web-application/resourcetechnologymapping'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'backend-web-application/resourcetechnologymapping'
 
images:
 - 'gcr.io/$PROJECT_ID/mvn:3.3.9-jdk-8'
- 'gcr.io/$PROJECT_ID/mvn'
