steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/resourcetechnologymapping:latest', '.']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
images: ['gcr.io/$PROJECT_ID/resourcetechnologymapping:latest']
