steps:
- name: "gcr.io/cloud-builders/go"
	env: ["PROJECT_ROOT=resourcetechnologymapping"]
	args: ["install","."]
	id: "go-install"
	
- name: "gcr.iocloud-builders/go"
	env: ["PROJECT_ROOT=resourcetechnologymapping"]
	args: ["test"]
	id: "go-test"
	
- name: "gcr.io/cloud-builders/docker"
	args: ["build", "-t","gcr.io/${PROJECT_ID}/resourcetechnologymapping:v1.0.0", "."]
	images: ["gcr.io/${PROJECT_ID}/resourcetechnologymapping:v1.0.0"]
