steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'resourcetechnologymapping'
   
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package',"-t", "gcr.io/$PROJECT_ID/my-image:$REVISION_ID", "."]
  dir: 'resourcetechnologymapping'
#- name: "gcr.io/cloud-builders/mvn"
 # args: ["build", "."]
 # dir: 'resourcetechnologymapping'
timeout: "1600s"
