# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Pull the latest gcloud image.
#- name: 'gcr.io/cloud-builders/docker'
 # args: ['pull', 'gcr.io/cloud-builders/gcloud']
#- name: 'gcr.io/cloud-builders/docker'
 # args: ['build', '--tag=gcr.io/$PROJECT_ID/git', '.']

# Clone a public repo and write its revision to a VERSION file.
#- name: 'gcr.io/$PROJECT_ID/git'
 # args: ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders.git']
  #dir: 'examples/version-file'
#images: ['gcr.io/$PROJECT_ID/git']

steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
 dir: 'resourcetechnologymapping'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-boot', '.']
  dir: 'resourcetechnologymapping'
images: ['gcr.io/$PROJECT_ID/spring-boot']
