steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetechnologymapping'
artifacts:
  objects:
   location: 'gs://mindtreegcp/'
   paths:
   - "${_TARGET}"
   - name: "gcr.io/cloud-builders/gcloud"
    args: [ 'compute', 'instances', 'create', 'front-end-instance-cb', '--create-disk=[image=gcp-backend-image,image-family=gcp-backend-image]', '--machine-type=n1-standard-1', '--metadata=[startup-script-url=gs://mindtree-gcp-project-135/startup-cloudbuild-script.sh'] 
