steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'resourcetechnologymapping'
- name: "gcr.io/cloud-builders/gcloud"  
  args: [ 'compute', 'instances', 'create', 'backend-web-app-instance-cb', '--image=gcp-backend-image', '--machine-type=n1-standard-1','--zone=asia-south1-c',--metadata-from-file startup-script=/home/M1048135/start.sh' ]
artifacts:
  objects:
   location: 'gs://m1048135/'
   paths:
   - "${_TARGET}"
