steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/resourcetechnologymapping', '.']
images: ['gcr.io/$PROJECT_ID/resourcetechnologymapping']
